-- Migration: Add status tracking fields for AI-generated questions
-- Date: 2025-10-26
-- Purpose: Enable teacher review workflow for AI-generated questions

-- Add status column to track question approval state
-- Values: 'unreviewed' (AI-generated, pending review), 'active' (approved, visible to students), 'archived' (hidden)
ALTER TABLE questions
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active' NOT NULL;

-- Add flag to track if question was AI-generated
ALTER TABLE questions
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE NOT NULL;

-- Add timestamp for when question was generated by AI
ALTER TABLE questions
ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP;

-- Update existing questions to have 'active' status (backward compatibility)
UPDATE questions
SET status = 'active', is_ai_generated = FALSE
WHERE status IS NULL OR status = '';

-- Add index on status column for efficient filtering
CREATE INDEX IF NOT EXISTS idx_questions_status ON questions(status);

-- Add composite index for common query pattern (module + status)
CREATE INDEX IF NOT EXISTS idx_questions_module_status ON questions(module_id, status);

-- Add comment to document the status values
COMMENT ON COLUMN questions.status IS 'Question review status: unreviewed (pending teacher review), active (approved and visible to students), archived (hidden but not deleted)';
COMMENT ON COLUMN questions.is_ai_generated IS 'Flag indicating if this question was generated by AI (true) or created manually (false)';
COMMENT ON COLUMN questions.generated_at IS 'Timestamp when the question was generated by AI, NULL for manually created questions';
